version: '3.8'

services:
    jubileu:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs
        restart: unless-stopped
        env_file: .env
        environment:
            - DB_HOST=db
            - DB_PORT=$DB_PORT
            - DB_DATABASE=$DB_DATABASE
            - PORT=$PORT
        ports:
            - "3000:3000"
        volumes:
            - .:/usr/app
            - node_modules:/usr/app/node_modules
        networks:
            - app-network
        command: npm run dev
        depends_on:
            - db
            - db-seed

    db:
        image: mongo:4.1.8-xenial
        container_name: db
        restart: unless-stopped
        env_file: .env
        environment:
        - MONGO_INITDB_DATABASE=$DB_DATABASE
        ports:
        - '27017:27017'
        volumes:
        - dbdata:/data/db
        networks:
        - app-network

    db-seed:
        build: ./seeds
        networks:
            - app-network
        depends_on:
        - db

networks:
    app-network:
        driver: bridge

volumes:
    dbdata:
    node_modules: